### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [3, -1, -1].  Tensor sizes: [2, 128, 128]

### ISSUE THREAD

**Issue by catthou** [lucidrains/stylegan2-pytorch#108]
Alright, I'm completely stuck. I keep running into this error. I don't know much about how GANs work but the error makes me think something is wrong with one of my data samples. I've been trying to refine my selection but when there's well over 3000 samples I can't really go through one-by-one to try to find some outlier.

I initially thought it was being picky against grayscale images, so I filtered them out, but to no avail.

I've tried with and without --transparency in case somehow an image containing some made it in, but output is not different.

Then I thought maybe it was trying to include sub-directories in the data folder, so I removed those, and nothing changed.

I adjusted batch size and related components in case this was a memory-related error but active memory use remains ~3GB and the error persists.

A data pool of ~100 images picked from a different source made it through to iteration 3000+ without encountering this breakage, so that furthers my assumption one of my samples is broken.

I'd appreciate some insight on what these dimensions are and how I can go about troubleshooting.

```
$ stylegan2_pytorch --data /media/LinuxDATA/nebula/x/generic_old/AAA-normal-stylegan --name illusfront --attn-layers [1,2] --aug-prob 0.2 --batch-size 1 --gradient-accumulate-every 15 --network-capacity 48 --new

illusfront</media/LinuxDATA/nebula/x/generic_old/AAA-normal-stylegan>:   0%|         | 0/150000 [00:00<?, ?it/s]/home/haruka/.local/lib/python3.6/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/haruka/.local/lib/python3.6/site-packages/adamp/adamp.py:80: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
G: 104.41 | D: 9.24 | GP: 371.04 | PL: 0.00 | CR: 0.00 | Q: 0.00
illusfront</media/LinuxDATA/nebula/x/generic_old/AAA-normal-stylegan>:   0%| | 25/150000 [03:56<394:52:38,  9.48
Traceback (most recent call last):
  File "/home/haruka/.local/bin/stylegan2_pytorch", line 92, in <module>
    fire.Fire(train_from_folder)
  File "/home/haruka/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/haruka/.local/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/haruka/.local/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/haruka/.local/bin/stylegan2_pytorch", line 87, in train_from_folder
    retry_call(model.train, tries=3, exceptions=NanException)
  File "/home/haruka/.local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/home/haruka/.local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/haruka/.local/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 749, in train
    image_batch = next(self.loader).cuda()
  File "/home/haruka/.local/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 113, in cycle
    for i in iterable:
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haruka/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haruka/.local/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 244, in __getitem__
    return self.transform(img)
  File "/home/haruka/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/haruka/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 359, in __call__
    return self.lambd(img)
  File "/home/haruka/.local/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 212, in __call__
    return tensor.expand(self.num_channels, -1, -1)
RuntimeError: The expanded size of the tensor (3) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [3, -1, -1].  Tensor sizes: [2, 128, 128]
```

**Comment by lucidrains** [comment]
Hi Haruka! One of your images somehow only has 2 channels, which I've never seen before. Could you identify which image cause the error? I'm happy to add support for that type of image, if we can figure out what extension it is and how to convert it to RGB

**Comment by catthou** [comment]
Hi! Thanks for the heads up. I suspected as much but it was quite a rabbit hole finding out about possible image types, so I didn't want to jump down if I didn't have to.... but here's the results.

The 2-channel image type is a grayscale+alpha PNG. It's Color Type 4 on [The PNG Chunk Specification](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html). The first channel is Gray, the second channel is Alpha. Perhaps here is the interesting part, maybe all you need:
```
  Type: GrayscaleAlpha
  Channel depth:
    gray: 8-bit
    alpha: 1-bit
```
You're welcome to add support for it or just close this ticket; I'm going to remove those images from my data set since this is an experimental data set and they're particularly low quality and the lack of color also means they lack some interpretable qualities. So do as you will!


--
Here's some additional information from my local system if this ever becomes relevant:
I attempted to recreate a 2-channel image to experiment on 
```
$ file grayscale-gradient.png 
grayscale-gradient.png: PNG image data, 128 x 128, 8-bit gray+alpha, non-interlaced
$ identify grayscale-gradient.png 
grayscale-gradient.png PNG 128x128 128x128+0+0 8-bit sRGB 33.1KB 0.000u 0:00.000

$ file sample_gs_1.png
sample_gs_1.png: PNG image data, 618 x 572, 8-bit/color RGBA, non-interlaced
$ identify sample_gs_1.png
sample_gs_1.png PNG 618x572 618x572+0+0 8-bit sRGB 163KB 0.000u 0:00.000
```
Above you can see one oddity with the sample file vs my recreation: the data sample shows up as RGBA from `file` but this is not wrong: the sample has 4 channels when opened in GIMP, but they get compressed on save because R=G=B, thus gray.


Attempting to convert a GrayscaleAlpha file to color results in no changes, just obliterating the alpha channel (as expected?):
```
$ convert grayscale-gradient.png -type TrueColorAlpha grayscale-gradient_color.png 
$ identify grayscale-gradient_color.png
grayscale-gradient_color.png PNG 128x128 128x128+0+0 8-bit sRGB 256c 3.48KB 0.000u 0:00.000
```
On the real sample, the 4-channel colorspace is optimized out for single-channel Gray colorspace, making it identical to the attempted recreation:
```
$ convert sample_gs_1.png -type TrueColorAlpha sample_gs_1_color.png
$ identify sample_gs_1_color.png 
sample_gs_1_color.png PNG 618x572 618x572+0+0 8-bit sRGB 256c 85.8KB 0.000u 0:00.000
```

**Comment by lucidrains** [comment]
@catthou i can add support for this, for both the transparent and non-transparent case! stay tuned

**Comment by lucidrains** [comment]
@catthou ok, done! https://github.com/lucidrains/stylegan2-pytorch/releases/tag/0.18.4 let me know if it works / doesn't work

**Comment by catthou** [comment]
Alright, I pulled out all the problematic images and set it loose on 'em. It seems to be spitting out models just fine, so thanks!
