### ISSUE TITLE
num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by josephrocca** [lucidrains/stylegan2-pytorch#11]
Steps to reproduce:
```bash
sudo docker run --gpus all --rm -it anibali/pytorch:cuda-10.1 bash
# Use `docker cp` to copy images across to container: sudo docker cp /path/to/images container_name:/app/images
pip install stylegan2_pytorch
stylegan2_pytorch --data ./images
```

Then, after 10k images processed of 100k total, I ran this:
```bash
stylegan2_pytorch --generate
```

and I got this error:
```
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 55, in <module>
    fire.Fire(train_from_folder)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 33, in train_from_folder
    num_workers = num_workers
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 406, in __init__
    self.loader = cycle(data.DataLoader(self.dataset, num_workers = default(num_workers, num_cores), batch_size = batch_size, drop_last = True, shuffle=True, pin_memory=True))
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
The images being trained are 1024x1024. The images in `./results/default` are being generated correctly (it's up to `10.jpg` after 10k images processed), and training seems to be proceeding with no problems. The `./models/default` folder contains `model_0.pt` and `model_1.pt`.

Thanks!

**Comment by lucidrains** [comment]
oh, that's a bug on my end, i'll fix it soon!

**Comment by lucidrains** [comment]
Should be fixed with https://github.com/lucidrains/stylegan2-pytorch/commit/ebc1e8181579b96a8d799f789bda2b352db3a69c !

**Comment by josephrocca** [comment]
Thanks!!
