### ISSUE TITLE
Error ttur_mult

### ISSUE THREAD

**Issue by ghujka** [lucidrains/stylegan2-pytorch#110]
Hello, I was able to train and generate normally but recently I am getting this error, couldn't solve it.

```
C:\Users\user\Desktop\stylegan2-pytorch-master\stylegan2_pytorch>python C:\Users\user\Desktop\stylegan2-pytorch-master\bin\stylegan2_pytorch --data C:\data
Traceback (most recent call last):
  File "C:\Users\user\Desktop\stylegan2-pytorch-master\bin\stylegan2_pytorch", line 92, in <module>
    fire.Fire(train_from_folder)
  File "C:\Users\user\anaconda3\envs\stylegan\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\user\anaconda3\envs\stylegan\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\Users\user\anaconda3\envs\stylegan\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\user\Desktop\stylegan2-pytorch-master\bin\stylegan2_pytorch", line 64, in train_from_folder
    model.load(load_from)
  File "C:\Users\user\anaconda3\envs\stylegan\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 960, in load
    self.load_config()
  File "C:\Users\user\anaconda3\envs\stylegan\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 673, in load_config
    self.init_GAN()
  File "C:\Users\user\anaconda3\envs\stylegan\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 658, in init_GAN
    self.GAN = StyleGAN2(lr=self.lr, image_size = self.image_size, network_capacity = self.network_capacity, transparent = self.transparent, fq_layers = self.fq_layers, fq_dict_size = self.fq_dict_size, attn_layers = self.attn_layers, fp16 = self.fp16, cl_reg = self.cl_reg, no_const = self.no_const, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ttur_mult'
```

Any help appreciated.

**Comment by lucidrains** [comment]
oops, should be fixed! https://github.com/lucidrains/stylegan2-pytorch/releases/tag/0.18.5
