### ISSUE TITLE
running into error "Exception: image with invalid number of channels given 4"

### ISSUE THREAD

**Issue by erinbeesley** [lucidrains/stylegan2-pytorch#148]
this is most def a error pertaining to a bad image in my dataset, but i'm not sure how I should get rid of bad images. any ideas?

**Comment by lucidrains** [comment]
I think you must have a transparent image somewhere in your dataset, but it should have converted that to RGB for you, so I'm not sure why you saw that error. Could you paste the full trace?

**Comment by erinbeesley** [comment]
```
Traceback (most recent call last):
  File "C:/Users/mason/AppData/Local/Programs/Python/Python37/Scripts/stylegan2_pytorch", line 96, in <module>
    fire.Fire(train_from_folder)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:/Users/mason/AppData/Local/Programs/Python/Python37/Scripts/stylegan2_pytorch", line 91, in train_from_folder
    retry_call(model.train, tries=3, exceptions=NanException)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\retry\api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 788, in train
    image_batch = next(self.loader).cuda()
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 113, in cycle
    for i in iterable:
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 11.
Original Traceback (most recent call last):
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 263, in __getitem__
    return self.transform(img)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "C:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torchvision\transforms\transforms.py", line 359, in __call__
    return self.lambd(img)
  File "C:\users\mason\appdata\local\programs\python\pytho
```

**Comment by lucidrains** [comment]
@erinbeesley want to update and give it another try? https://github.com/lucidrains/stylegan2-pytorch/releases/tag/1.2.2

**Comment by erinbeesley** [comment]
> @erinbeesley want to update and give it another try? https://github.com/lucidrains/stylegan2-pytorch/releases/tag/1.2.2

getting this now: `Traceback (most recent call last):
  File "c:\users\mason\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mason\AppData\Local\Programs\Python\Python37\Scripts\stylegan2_pytorch.exe\__main__.py", line 7, in <module>
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\cli.py", line 169, in main
    fire.Fire(train_from_folder)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\cli.py", line 160, in train_from_folder
    run_training(0, 1, model_args, data, load_from, new, num_train_steps, name)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\cli.py", line 52, in run_training
    model.load(load_from)
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 1195, in load
    self.GAN.load_state_dict(load_data['GAN'])
  File "c:\users\mason\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for StyleGAN2:
        Missing key(s) in state_dict: "G.blocks.0.to_rgb.upsample.1.f", "G.blocks.1.to_rgb.upsample.1.f", "G.blocks.2.to_rgb.upsample.1.f", "G.blocks.3.to_rgb.upsample.1.f", "G.blocks.4.to_rgb.upsample.1.f", "D.blocks.0.downsample.0.f", "D.blocks.0.downsample.1.weight", "D.blocks.0.downsample.1.bias", "D.blocks.1.downsample.0.f", "D.blocks.1.downsample.1.weight", "D.blocks.1.downsample.1.bias", "D.blocks.2.downsample.0.f", "D.blocks.2.downsample.1.weight", "D.blocks.2.downsample.1.bias", "D.blocks.3.downsample.0.f", "D.blocks.3.downsample.1.weight", "D.blocks.3.downsample.1.bias", "D.blocks.4.downsample.0.f", "D.blocks.4.downsample.1.weight", "D.blocks.4.downsample.1.bias", "D.blocks.5.downsample.0.f", "D.blocks.5.downsample.1.weight", "D.blocks.5.downsample.1.bias", "GE.blocks.0.to_rgb.upsample.1.f", "GE.blocks.1.to_rgb.upsample.1.f", "GE.blocks.2.to_rgb.upsample.1.f", "GE.blocks.3.to_rgb.upsample.1.f", "GE.blocks.4.to_rgb.upsample.1.f", "D_aug.D.blocks.0.downsample.0.f", "D_aug.D.blocks.0.downsample.1.weight", "D_aug.D.blocks.0.downsample.1.bias", "D_aug.D.blocks.1.downsample.0.f", "D_aug.D.blocks.1.downsample.1.weight", "D_aug.D.blocks.1.downsample.1.bias", "D_aug.D.blocks.2.downsample.0.f", "D_aug.D.blocks.2.downsample.1.weight", "D_aug.D.blocks.2.downsample.1.bias", "D_aug.D.blocks.3.downsample.0.f", "D_aug.D.blocks.3.downsample.1.weight", "D_aug.D.blocks.3.downsample.1.bias", "D_aug.D.blocks.4.downsample.0.f", "D_aug.D.blocks.4.downsample.1.weight", "D_aug.D.blocks.4.downsample.1.bias", "D_aug.D.blocks.5.downsample.0.f", "D_aug.D.blocks.5.downsample.1.weight", "D_aug.D.blocks.5.downsample.1.bias".
        Unexpected key(s) in state_dict: "D.blocks.0.downsample.weight", "D.blocks.0.downsample.bias", "D.blocks.1.downsample.weight", "D.blocks.1.downsample.bias", "D.blocks.2.downsample.weight", "D.blocks.2.downsample.bias", "D.blocks.3.downsample.weight", "D.blocks.3.downsample.bias", "D.blocks.4.downsample.weight", "D.blocks.4.downsample.bias", "D.blocks.5.downsample.weight", "D.blocks.5.downsample.bias", "D_aug.D.blocks.0.downsample.weight", "D_aug.D.blocks.0.downsample.bias", "D_aug.D.blocks.1.downsample.weight", "D_aug.D.blocks.1.downsample.bias", "D_aug.D.blocks.2.downsample.weight", "D_aug.D.blocks.2.downsample.bias", "D_aug.D.blocks.3.downsample.weight", "D_aug.D.blocks.3.downsample.bias", "D_aug.D.blocks.4.downsample.weight", "D_aug.D.blocks.4.downsample.bias", "D_aug.D.blocks.5.downsample.weight", "D_aug.D.blocks.5.downsample.bias".
`

**Comment by lucidrains** [comment]
pass a `--new` to restart your training from scratch, it must have mis-saved

**Comment by erinbeesley** [comment]
will do

**Comment by erinbeesley** [comment]
this works! just seems like its running on CPU now? might be a error with my installation. i'll figure it out. thanks!
