### ISSUE TITLE
Apply multi-gpus and return "name seed is not defined".

### ISSUE THREAD

**Issue by szxuhongye** [lucidrains/stylegan2-pytorch#149]

**Comment by lucidrains** [comment]
can you post the full trace?

**Comment by szxuhongye** [comment]
(augment) an499@mister:~/Desktop$ stylegan2_pytorch --data ./images --name test3 --image-size 256 --aug-prob 0.25 --calculate-fid-every 1000 --multi-gpus --new
Traceback (most recent call last):
  File "/common/users/an499/anaconda3/envs/augment/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/stylegan2_pytorch/cli.py", line 169, in main
    fire.Fire(train_from_folder)
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/stylegan2_pytorch/cli.py", line 163, in train_from_folder
    mp.spawn(run_training,
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/common/users/an499/anaconda3/envs/augment/lib/python3.8/site-packages/stylegan2_pytorch/cli.py", line 36, in run_training
    set_seed(seed)
NameError: name 'seed' is not defined

**Comment by lucidrains** [comment]
https://github.com/lucidrains/stylegan2-pytorch/releases/tag/1.2.3 ok, i made an update, want to retry?

**Comment by lucidrains** [comment]
@szxuhongye does it work now?

**Comment by szxuhongye** [comment]
> @szxuhongye does it work now?

It works! Thank you so much!

**Comment by lucidrains** [comment]
Hurray! Enjoy the spectacle :)
