### ISSUE TITLE
How can it work on my own dataset?

### ISSUE THREAD

**Issue by Yugt4732** [lucidrains/stylegan2-pytorch#152]
There are about 20k pieces photo, and the resolution is 1024*1024. How can I train network? An AssertionError：assert isinstance(lambd, types.LambdaType). What is the process if I use my own dataset?

**Comment by lucidrains** [comment]
@Yugt4732 could you paste the full error trace?

**Comment by Yugt4732** [comment]
Here's the error I met.
____________________________________________
Traceback (most recent call last):
  File "/home/momobot/anaconda3/envs/train/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 157, in main
    fire.Fire(train_from_folder)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 148, in train_from_folder
    run_training(0, 1, model_args, data, load_from, new, num_train_steps, name)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 56, in run_training
    model.set_data_src(data)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 757, in set_data_src
    self.dataset = Dataset(folder, self.image_size, transparent = self.transparent, aug_prob = self.dataset_aug_prob)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 281, in __init__
    transforms.Lambda(partial(resize_to_minimum_size, image_size)),
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 279, in __init__
    assert isinstance(lambd, types.LambdaType)
AssertionError

**Comment by vio-codes** [comment]
Maybe you can check if you have PNG files between the JPG, or maybe some of the images are corrupted.
Did you curated the dataset?
