### ISSUE TITLE
Multi-GPU fails on pytorch 1.7

### ISSUE THREAD

**Issue by its-dron** [lucidrains/stylegan2-pytorch#164]
Set up a fresh conda environment with latest versions of all libraries, and found multi-gpu training didn't work anymore. Rolling pytorch back to 1.6 fixed the issue. 

The error:

```python
% stylegan2_pytorch --data ./my/data --num_workers 32 --batch_size 64 --save_every 500 --name drawn --multi-gpus --gradient-accumulate-every 1

2/4 process initialized.
4/4 process initialized.
1/4 process initialized.
3/4 process initialized.
drawn<./my/data>:   0%|                                                                                                                                                                               | 0/150000 [00:00<?, ?it/s]
drawn<./my/data>:   0%|                                                                                                                                                                               | 0/150000 [00:00<?, ?it/s]
drawn<./my/data>:   0%|                                                                                                                                                                               | 0/150000 [00:00<?, ?it/s]
drawn<./my/data>:   0%|                                                                                                                                                                               | 0/150000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/danron/miniconda3/envs/style/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/stylegan2_pytorch/cli.py", line 172, in main
    fire.Fire(train_from_folder)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/stylegan2_pytorch/cli.py", line 166, in train_from_folder
    mp.spawn(run_training,
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/stylegan2_pytorch/cli.py", line 59, in run_training
    retry_call(model.train, tries=3, exceptions=NanException)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 876, in train
    fake_output, fake_q_loss = D_aug(generated_images.clone().detach(), detach = True, **aug_kwargs)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/danron/miniconda3/envs/style/lib/python3.8/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 333, in forward
    images.detach_()
RuntimeError: If you are using DistributedDataParallel (DDP) for training, and gradient_as_bucket_view is set as True, gradients are views of DDP buckets, and hence detach_() cannot be called on these gradients. To fix this error, please refer to the Optimizer.zero_grad() function in torch/optim/optimizer.py as the solution.
```

The version rollback: 
```
  pytorch              1.7.0-py3.8_cuda10.2.89_cudnn7.6.5_0 --> 1.6.0-py3.8_cuda10.2.89_cudnn7.6.5_0
  torchaudio                                     0.7.0-py38 --> 0.6.0-py38
  torchvision                              0.8.1-py38_cu102 --> 0.7.0-py38_cu102
```

I believe the pytorch change that caused this issue is this one: https://github.com/pytorch/pytorch/commit/c6500bcf1494aadf7bd86adb554fdad376b7f105

**Comment by lucidrains** [comment]
@its-dron Hi Daniel! Do you want to give 1.2.8 a quick try? https://github.com/lucidrains/stylegan2-pytorch/releases/tag/1.2.8

**Comment by gspeed0689** [comment]
@lucidrains I was experiencing the exact same issue and so far your version 1.2.8 is working well on Ubuntu 20.04 in an AWS g4dn.12xlarge instance.

**Comment by lucidrains** [comment]
@gspeed0689 nice :) happy disentangling

**Comment by therealjjj77** [comment]
I'm also having this issue with Torch 1.7.1+cu110. The 1.2.8 version did not fix it. Please see below:

(venv) C:\Users\Jerr\PycharmProjects\pythonProject1>stylegan2_pytorch --data C:/Transfer/Downloads/Processed/Compressed/Compressed --network-capacity 256 --trunc-psi 0.5 --aug-prob 0.25 --attn-layers 1 --top-k-training --generate-top-k
-frac 0.5 --generate-top-k-gamma 0.99 --no-pl-reg --calculate-fid-every 5000 --multi-gpus --num_workers 32
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jerr\PycharmProjects\pythonProject1\venv\Scripts\stylegan2_pytorch.exe\__main__.py", line 7, in <module>
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\stylegan2_pytorch\cli.py", line 172, in main
    fire.Fire(train_from_folder)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\stylegan2_pytorch\cli.py", line 169, in train_from_folder
    join=True)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 157, in start_processes
    while not context.join():
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 19, in _wrap
    fn(i, *args)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\stylegan2_pytorch\cli.py", line 39, in run_training
    dist.init_process_group('nccl', rank=rank, world_size=world_size)
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "c:\users\jerr\pycharmprojects\pythonproject1\venv\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
