### ISSUE TITLE
Windows: pip install doesn't work

### ISSUE THREAD

**Issue by pocaha** [lucidrains/stylegan2-pytorch#178]
The following is output from the anaconda prompt:
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\bibi\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bibi\\AppData\\Local\\Temp\\pip-install-ma3x6o5s\\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\\setup.py'"'"'; __file__='"'"'C:\\Users\\bibi\\AppData\\Local\\Temp\\pip-install-ma3x6o5s\\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\bibi\AppData\Local\Temp\pip-pip-egg-info-y5m73gya'
         cwd: C:\Users\bibi\AppData\Local\Temp\pip-install-ma3x6o5s\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bibi\AppData\Local\Temp\pip-install-ma3x6o5s\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\setup.py", line 34, in <module>
        packages=setuptools.find_packages(where='src/'),
      File "C:\Users\bibi\anaconda3\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\Users\bibi\anaconda3\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by trufty** [comment]
Looks like pytorch-fid just fixed this in their [repo](https://github.com/mseitzer/pytorch-fid/commit/732341f2129bc8b41cbbfaa4d738788645cb1df7)  Not sure if its available in pip yet.

**Comment by pocaha** [comment]
Hi! 
It is available in pip, but there is another problem. This time it is _fire_ ...

> ERROR: Requested decorator from https://files.pythonhosted.org/packages/ed/69/24345e0d49c700557f135d01f5de03345368303fdee81b54eae28bf6143d/decorator-4.0.8-py2.py3-none-any.whl#sha256=267b0d56f2c44857f0803cefe5ee1b5d661fd17ef78be3b447d295f70d4a9a5d (from ipython<6.0->fire->stylegan2_pytorch) has different version in metadata: '4.0.7'

**Comment by trufty** [comment]
I'm getting the same thing, but that looks like a deep rabbit hole.  I just ended up downloading this repo and training via `python ./stylegan2_pytorch/cli.py <+ params>`

You'll have to alter a few import paths, install setup.py packages, and add `if __name__ == "__main__":`  to cli.py:175 to get it running.

Good luck

**Comment by canadaduane** [comment]
As a temporary workaround, this was sufficient for me:
```
python -m pip install git+https://github.com/mseitzer/pytorch-fid.git@732341f2129bc8b41cbbfaa4d738788645cb1df7
```

**Comment by sharpe5** [comment]
See: https://github.com/lucidrains/stylegan2-pytorch/issues/155

**Comment by Peridot03** [comment]
I am having the same issue. I was able to install torchvision ok, but now I am stuck installing stylegan. I have tried the other work arounds listed in the threads, but my issue persists. Everything is up to date, and I am using the latest version of JupyterLab Desktop.
