### ISSUE TITLE
RTX3090 training issues

### ISSUE THREAD

**Issue by LeMagicienHuang** [lucidrains/stylegan2-pytorch#200]
Environment:
Anaconda & Python3.7
CUDA 11.2 & cudnn 8.0.5
torch-gpu 1.7.1 & torchvision 0.8.2

When I run the training command 

stylegan2_pytorch --data images/128a --image-size 128 --num-train-steps 100000

error occurred:

default<images/128a>:   0%|                                                                 | 0/100000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
default<images/128a>:   0%|                                                                 | 0/100000 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "e:\users\admin\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
  File "e:\users\admin\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
        exitcode = _main(fd)
"__main__", mod_spec)  File "e:\users\admin\anaconda3\lib\multiprocessing\spawn.py", line 115, in _main

    self = reduction.pickle.load(from_parent)
  File "e:\users\admin\anaconda3\lib\runpy.py", line 85, in _run_code
  File "e:\users\admin\anaconda3\lib\site-packages\torch\__init__.py", line 117, in <module>
        raise err
exec(code, run_globals)OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "e:\users\admin\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

  File "E:\Users\admin\anaconda3\Scripts\stylegan2_pytorch.exe\__main__.py", line 7, in <module>
  File "e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\cli.py", line 181, in main
    fire.Fire(train_from_folder)
  File "e:\users\admin\anaconda3\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "e:\users\admin\anaconda3\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "e:\users\admin\anaconda3\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\cli.py", line 172, in train_from_folder
    run_training(0, 1, model_args, data, load_from, new, num_train_steps, name, seed)
  File "e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\cli.py", line 59, in run_training
    retry_call(model.train, tries=3, exceptions=NanException)
  File "e:\users\admin\anaconda3\lib\site-packages\retry\api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "e:\users\admin\anaconda3\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 943, in train
    image_batch = next(self.loader).cuda(self.rank)
  File "e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 148, in cycle
    for i in iterable:
  File "e:\users\admin\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "e:\users\admin\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "e:\users\admin\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "e:\users\admin\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "e:\users\admin\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "e:\users\admin\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "e:\users\admin\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "e:\users\admin\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

anyone can help? thx in advance.

**Comment by LeMagicienHuang** [comment]
Problem solved.

In files:

e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\cli.py
e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py

num_workers = None  **→** num_workers = 0

**Comment by seobkim** [comment]
> 문제 해결됨.
> 
> 파일에서 :
> 
> e : \ users \ admin \ anaconda3 \ lib \ site-packages \ stylegan2_pytorch \ cli.py
> e : \ users \ admin \ anaconda3 \ lib \ site-packages \ stylegan2_pytorch \ stylegan2_pytorch.py
> 
> 기본값 :
> num_workers = None
> 
> 보정:
> 
> num_workers = 0

**Comment by seobkim** [comment]
> Problem solved.
> 
> In files:
> 
> e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\cli.py
> e:\users\admin\anaconda3\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py
> 
> Default:
> num_workers = None
> 
> Correction:
> 
> num_workers = 0

thanks you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
