### ISSUE TITLE
Help generating images

### ISSUE THREAD

**Issue by luchoster** [lucidrains/stylegan2-pytorch#21]
My project finished training (completed at 100%), I can see all the generated images in the correct folders (yeah I ran them inside the `bin` folder).

But when I try to generate, it fails:

```
C:\Users\luiss\DevStuff\stylegan\bin>py stylegan2_pytorch --generate
continuing from previous epoch - 9
Traceback (most recent call last):
  File "stylegan2_pytorch", line 56, in <module>
    fire.Fire(train_from_folder)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 138, in Fire        component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 471, in _Fire       target=component.__name__)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "stylegan2_pytorch", line 44, in train_from_folder
    model.evaluate(samples_name)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 589, in evaluate
    torchvision.utils.save_image(generated_images, str(self.results_dir / self.name / f'{str(num)}.jpg'), nrow=num_rows)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\utils.py", line 109, in save_image
    im.save(fp, format=format)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2099, in save       fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'results\\default\\generated-02-21-2020_09:01:40.jpg'
```

any ideas?

**Comment by lucidrains** [comment]
@luchoster oh i understand! windows doesn't like `:` in the file name, let me get rid of that

**Comment by lucidrains** [comment]
@luchoster updated! try again!

**Comment by luchoster** [comment]
Awesome, thanks. I'll try right now

**Comment by luchoster** [comment]
now I'm getting this, trying it with `--num-image-tiles` and without that flag too.

```
continuing from previous epoch - 9
Traceback (most recent call last):
  File "stylegan2_pytorch", line 57, in <module>
    fire.Fire(train_from_folder)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 138, in Fire         component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 471, in _Fire        target=component.__name__)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "stylegan2_pytorch", line 45, in train_from_folder
    model.evaluate(samples_name, num_image_tiles=num_image_tiles)
  File "C:\Users\luiss\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
TypeError: evaluate() got an unexpected keyword argument 'num_image_tiles'
```

**Comment by lucidrains** [comment]
@luchoster hmm, I made another update, can you try again?

**Comment by luchoster** [comment]
That did it!
Images generated are ugly but it's awesome!!!! haha

**Comment by lucidrains** [comment]
Awesome! How big is your training set btw?

**Comment by luchoster** [comment]
![generated-02-21-2020_09-57-44](https://user-images.githubusercontent.com/694367/75059011-ea3b4c80-5490-11ea-8a57-91f0aa8fd374.jpg)
![generated-02-21-2020_09-57-44-ema](https://user-images.githubusercontent.com/694367/75059012-ead3e300-5490-11ea-8f42-95bfff68ba8d.jpg)
![generated-02-21-2020_09-57-44-mr](https://user-images.githubusercontent.com/694367/75059013-eb6c7980-5490-11ea-8352-915ba2e29221.jpg)


Here are the best I could get so far. I have 285 pictures, it took about 40 hrs to train and the bestish models were 3 and 4 maybe even 5 a little, but I'm guessing that's as good as is going to get? Is there anything you recommend to make it better?

**Comment by lucidrains** [comment]
@luchoster wow, 300 is not a lot at all, you'll need up to 10k or more, and at a greater image size for better results!

**Comment by lucidrains** [comment]
@luchoster i'm surprised it learned anything at all

**Comment by luchoster** [comment]
ahhh ok ok, that's good to know too. So it did a really good job for what I gave it. I'm going to collect more pictures and try again. 

Thanks again for this, and sorry for being a pain with my Windows machine (I hate it but it's the only one with the right specs lol). You're awesome!

**Comment by lucidrains** [comment]
@luchoster thanks! don't hesitate to ping me if you run into any other trouble!

**Comment by WoshiBoluo** [comment]
> That did it!
> Images generated are ugly but it's awesome!!!! haha

Hello, I am a new guy. Could you please give me the steps on how to train and use it on Windows. I have already installed it in the current environment. Thank you very much.
