### ISSUE TITLE
stylegan2_pytorch --generate error

### ISSUE THREAD

**Issue by zhouyongxiu** [lucidrains/stylegan2-pytorch#219]
When I use 'stylegan2_pytorch --generate' to generate image with my own model, I got the error:

continuing from previous epoch - 150
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/gan/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 185, in main
    fire.Fire(train_from_folder)
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 158, in train_from_folder
    model.load(load_from)
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 1291, in load
    load_data = torch.load(self.model_name(name))
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/ubuntu/anaconda3/envs/gan/lib/python3.6/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/93899375642032: invalid header or archive is corrupted

can anybody help me?

**Comment by zhouyongxiu** [comment]
it can work

**Comment by BenfenYU** [comment]
Hi, I face the same problem. Can you tell me how do you fix it? Thank you.

**Comment by CasiaFan** [comment]
It's likely that the model file is corrupt. Try another weight file.
