### ISSUE TITLE
Size mismatch?

### ISSUE THREAD

**Issue by iboates** [lucidrains/stylegan2-pytorch#30]
I have just collected >10k images as recommended, but I'm now hitting this error, complaining that there is a "size mismatch". Any ideas? I verified that every image in my training set is exactly 418x418 pixels.

Rolling back to version 0.4.11 did not help.

```
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
!pip uninstall stylegan2_pytorch
!pip install stylegan2_pytorch
!stylegan2_pytorch --image-size 418 --data /content/drive/My\ Drive/BY/tiles --results-dir drive/My\ Drive/results --models-dir drive/My\ Drive/models --name 20200315_bayern_towns_villages
```

```
  0% 0/100000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/stylegan2_pytorch", line 59, in <module>
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/bin/stylegan2_pytorch", line 54, in train_from_folder
    model.train()
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 492, in train
    real_output = self.GAN.D(image_batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 341, in forward
    x = self.to_logit(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [3 x 32768], m2: [8192 x 1] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
```

**Comment by iboates** [comment]
After doing a bit more reading into SytleGAN itself I found that you are supposed to use perfectly square images with lengths of powers of 2. Is this the case? I could have sworn that I was training successfully with 418x418 images but maybe I was mistaken. If you can confirm this, I can make a PR to make a try/except block to catch this error and give a more descriptive error message advising that images need to conform to this standard.

**Comment by lucidrains** [comment]
@iboates yes, you are right! I should add a validation for that, or I would be glad to accept a PR as well!

**Comment by lucidrains** [comment]
done! https://github.com/lucidrains/stylegan2-pytorch/commit/acd7e3cc1faa79ca8a0eb1c52715dbde77403c30
