### ISSUE TITLE
TypeError: sum() received an invalid combination of arguments

### ISSUE THREAD

**Issue by sunyu516442436** [lucidrains/stylegan2-pytorch#32]
When I try to run this repository using the command,
$ stylegan2_pytorch --data /path/to/images
it failed with the following error.
I am wondered whether the input image size must be 1024*1024 in a square shape. May I use the rectangle image, and whether the rectangle image causes the error?
Looking forward to your reply. Thx very much for the repo.

Traceback (most recent call last):
  File "/home/sunyu/.local/bin/stylegan2_pytorch", line 59, in <module>
    fire.Fire(train_from_folder)
  File "/home/sunyu/.local/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/sunyu/.local/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/sunyu/.local/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/sunyu/.local/bin/stylegan2_pytorch", line 54, in train_from_folder
    model.train()
  File "/home/sunyu/.local/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 488, in train
    generated_images = self.GAN.G(w_styles, noise).detach()
  File "/home/env/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sunyu/.local/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 310, in forward
    x, rgb = block(x, rgb, style, input_noise)
  File "/home/env/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sunyu/.local/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 244, in forward
    x = self.conv1(x, style1)
  File "/home/env/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sunyu/.local/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 205, in forward
    d = torch.rsqrt((weights ** 2).sum(dim=(2, 3, 4), keepdims=True) + EPS)
TypeError: sum() received an invalid combination of arguments - got (keepdims=bool, dim=tuple, ), but expected one of:
 * ()
 * (torch.dtype dtype)
 * (tuple of ints dim, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: keepdims
 * (tuple of ints dim, bool keepdim, torch.dtype dtype)
 * (tuple of ints dim, bool keepdim)
      didn't match because some of the keywords were incorrect: keepdims

**Comment by lucidrains** [comment]
@sunyu516442436 please update and try again! I believe I fixed a bug with an erroneously named keyword argument (keepdims). It must have been rescued by the broadcasting.
