### ISSUE TITLE
Pickle error

### ISSUE THREAD

**Issue by peter-ch** [lucidrains/stylegan2-pytorch#48]
I'm trying to run the command as specified in the documentation but I keep getting this error regardless of the PyTorch version installed:

Traceback (most recent call last):
  File "C:/Python36/Scripts/stylegan2_pytorch", line 66, in <module>
    fire.Fire(train_from_folder)
  File "C:\python36\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\python36\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\python36\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:/Python36/Scripts/stylegan2_pytorch", line 61, in train_from_folder
    retry_call(model.train, tries=3, exceptions=NanException)
  File "C:\python36\lib\site-packages\retry\api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "C:\python36\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\python36\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 529, in train
    image_batch = next(self.loader).cuda()
  File "C:\python36\lib\site-packages\stylegan2_pytorch\stylegan2_pytorch.py", line 63, in cycle
    for i in iterable:
  File "C:\python36\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\python36\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'expand_greyscale.<locals>.inner'

**Comment by dancrew32** [comment]
Looks like a recent adjustment near expand_greyscale. Are you sure you're using the exact same version of `stylegan2_pytorch` that your pickled object was created with?
https://github.com/lucidrains/stylegan2-pytorch/commit/a86eef2cfcacdfe96a9095d6ad0a00f20b77242f

**Comment by lucidrains** [comment]
@peter-ch fixed! https://github.com/lucidrains/stylegan2-pytorch/commit/2db7a548204b4b60e97a266f6036f93af2ae3cde
