### ISSUE TITLE
Torch optimizer error *novice*

### ISSUE THREAD

**Issue by Rowjee** [lucidrains/stylegan2-pytorch#51]
Hey!

I get this message when I try to install the repository; "ERROR: torch-optimizer 0.0.1a11 has requirement torch>=1.1.0, but you'll have torch 0.1.2.post2 which is incompatible."

I'm an absolute novice at this, but I'd really like to learn through something I'm interested in; Can any of you folks help me with this?

Thanks in advance!

**Comment by lucidrains** [comment]
you need to upgrade your torch! that's a reallly old version haha

**Comment by lucidrains** [comment]
`pip install torch --upgrade`

**Comment by Rowjee** [comment]
> `pip install torch --upgrade`

Hey, thanks for the quick reply!

I now get this error when I try to upgrade torch:

`Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied, skipping upgrade: pyyaml in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from torch) (5.3.1)
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-1pkorzcy\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-1pkorzcy\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-l38ep50b\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\Include\torch'`
Have any tips on this one? Thanks so much again for the help and quick reply

**Comment by erickulcyk** [comment]
Is that the full output?  Make sure you are running in an admin command prompt when you run the pip command

**Comment by Rowjee** [comment]
> Is that the full output? Make sure you are running in an admin command prompt when you run the pip command

Hey!

Ran the command in an administrator command prompt and I get the same error. And yeah, i didn't post the full error output, I'll link it here:

´Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-573q7ddx\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-573q7ddx\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-861365aq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\Include\torch'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-573q7ddx\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-573q7ddx\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Temp\pip-install-573q7ddx\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Temp\pip-install-573q7ddx\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-573q7ddx\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-573q7ddx\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-861365aq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\Include\torch' Check the logs for full command output.´

thanks for the reply!
