### ISSUE TITLE
OSError: Caught OSError in DataLoader worker process 0 / image file is truncated (1 bytes not processed)

### ISSUE THREAD

**Issue by josephrocca** [lucidrains/stylegan2-pytorch#7]
This is very fun to play with - thanks for making it so easy to set up! I've been training it for an hour or so and it's already generating some interesting results. I have no experience with pytorch or GANs (and barely any python experience) so your motto "simplest working implementation" definitely rings true for me - only took a couple of minutes (mainly sorting out docker) for me to get up and running.

Okay, on to the bug report. I got the following error after about 10k images processed:

```
G: 2.58 | D: 1.06 | GP: 0.00 | PL: 0.73
 10%|#########2                                 | 10449/100000 [1:56:39<15:46:03,  1.58it/s]G: 1.87 | D: 1.53 | GP: 0.00 | PL: 0.73
 10%|#########3                                 | 10497/100000 [1:57:09<15:46:00,  1.58it/s]G: 1.06 | D: 1.14 | GP: 0.00 | PL: 0.72
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 53, in <module>
    fire.Fire(train_from_folder)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 48, in train_from_folder
    model.train()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 441, in train
    image_batch = next(self.loader).cuda()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 74, in cycle
    for i in iterable:
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 129, in __getitem__
    return self.transform(img)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 687, in __call__
    return F.resized_crop(img, i, j, h, w, self.size, self.interpolation)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 407, in resized_crop
    img = crop(img, top, left, height, width)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 367, in crop
    return img.crop((left, top, left + width, top + height))
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/PIL/Image.py", line 1105, in crop
    self.load()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/PIL/ImageFile.py", line 247, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (1 bytes not processed)

 10%|#########3                              | 10497/100000 [1:57:15<16:39:48,  1.49it/s]
```

Here are my reproduction steps:

```bash
sudo docker run --gpus all --rm -it anibali/pytorch:cuda-10.1 bash
# Use `docker cp` to copy images across to container: sudo docker cp /home/joe/Downloads/images container_name:/app/images
pip install stylegan2_pytorch
stylegan2_pytorch --data ./images
```
Is this error perhaps caused by a corrupt image file? If so, maybe corrupt images could be skipped? Or the path of the image could be logged?

According to ImageMagic's `identify` command, all 100k images are valid jpgs. Tested using this command (from [here](https://stackoverflow.com/a/4780731/11950764)):

```
for f in /home/joe/Downloads/images/*.jpg ; do identify $f > /dev/null || echo $f >> /tmp/fail ; done ; cat /tmp/fail
```
Here's the output of the `file` command for one of the images (they're all the same size and type):

```
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1024x1024, components 3
```

I've started the processing again with `stylegan2_pytorch --data ./images`, and it's at 3k images processed (out of 90k - so I'm guessing checkpoints are every 10k images?), and no error yet. Will update this if I get another error. Should only be an hour or so until it has passed the 10k mark again.

Also, a separate, minor thing is that I noticed that it doesn't work for smaller images:

```bash
sudo docker run --gpus all --rm -it anibali/pytorch:cuda-10.1 bash
curl https://raw.githubusercontent.com/myleott/mnist_png/master/mnist_png.tar.gz > mnist_png.tar.gz
tar -xvzf mnist_png.tar.gz
pip install stylegan2_pytorch
stylegan2_pytorch --data ./mnist_png
```
That results in this:
```
  0%|                                                                                                | 0/100000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 53, in <module>
    fire.Fire(train_from_folder)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 48, in train_from_folder
    model.train()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 443, in train
    real_output = self.GAN.D(image_batch)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 324, in forward
    x = self.blocks(x)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 254, in forward
    res = self.conv_res(x)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 16 3 1 1, expected input[3, 1, 128, 128] to have 3 channels, but got 1 channels instead
```

Maybe the images could be scaled up (I'm guessing 128x128 is the minimum?), or a better error message could be added?

Thanks again for this! Having a bunch of fun with it :)

**Comment by josephrocca** [comment]
Okay this time it errored at 5599/90000 with the same error message.

Also, the `stylegan2_pytorch  --generate` command throws an error for me:

```
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 53, in <module>
    fire.Fire(train_from_folder)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/miniconda/envs/py36/bin/stylegan2_pytorch", line 31, in train_from_folder
    lr = learning_rate
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 398, in __init__
    self.dataset = Dataset(folder, image_size)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 115, in __init__
    raise Exception(f'no images found at {folder}')
Exception: no images found at ./data
```

In case it's useful info: The `./models/default` folder contains: `model_0.pt` and  `model_1.pt`, and it looks like the `./results/default` folder contains one `N.jpg` image per thousand training images processed (along with `N-ema.jpg` and `N-me.jpg`).

**Comment by lucidrains** [comment]
Hi Joseph! Thanks for your interest in this project! I've uploaded a fix so that it auto resizes all images in the folder to at least the target size being trained. You can also set image sizes to smaller than 128 with the `--image-size` flag. I've also fix the problem with `--generate`, it should work now.

I did some googling on your issue with the `truncated` error and it seems likely that one of your images may be corrupted, even if it passes the imagemagick tests. https://discuss.pytorch.org/t/oserror-image-file-is-truncated-28-bytes-not-processed-during-learning/36815/21 Could you go through that forum and try some of the suggestions there?

**Comment by josephrocca** [comment]
Thanks! I ran a variation of the code from the link you posted (pasted below) and it didn't detect any corrupt images. I'll look into this a bit more tomorrow and update you if I work out the cause.

```python
from PIL import Image
from pathlib import Path
for p in Path(f'./images').glob('*.jpg'):
  try:
    im = Image.open(p)
    im2 = im.convert('RGB')
  except OSError:
    print("Cannot load : {}".format(fn))
```

**Comment by josephrocca** [comment]
Okay, I think I see what happened here. I was testing the images on my host OS, and it wasn't finding any corruption, but the images I'm training on are inside the docker container, so there must have been a corruption during the `docker cp` process. I've started a new container and am up to 49k and no errors. Thanks for your help! This is a lot of fun!
