### ISSUE TITLE
Issues with larger datasets

### ISSUE THREAD

**Issue by pcicales** [lucidrains/stylegan2-pytorch#71]
Hello, I get the following error when training on a large dataset:

Traceback (most recent call last):
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/bin/stylegan2_pytorch", line 72, in <module>
    fire.Fire(train_from_folder)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/bin/stylegan2_pytorch", line 67, in train_from_folder
    retry_call(model.train, tries=3, exceptions=NanException)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 698, in train
    self.GAN.EMA()
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 495, in EMA
    ema_inplace_module(self.SE, self.S)
  File "/home/pietro/miniconda3/envs/stylegan2-pytorch-master/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 181, in ema_inplace_module
    ema_inplace(old_weight, up_weight)
TypeError: ema_inplace() missing 1 required positional argument: 'decay'

I will report back here as I debug. Im really not sure what the issue is.

**Comment by pcicales** [comment]
It seems that the error occurs after passing step 20,000. This is the relevant code:

`if self.steps % 10 == 0 and self.steps > 20000:
      self.GAN.EMA()`

**Comment by pcicales** [comment]
Just saw this was fixed in a recent commit.
