### ISSUE TITLE
Error(s) in loading state_dict for StyleGAN2

### ISSUE THREAD

**Issue by NickAcPT** [lucidrains/stylegan2-pytorch#83]
I've been training my model on transparent images and this happened.
[Here](https://drive.google.com/file/d/1ztOY8I9dyhS8IaCC6eq__NZ2cpHH8bJo/view?usp=sharing) is the model. The commit that introduced this was d3207f4505b7c01723e1983e8a6d70ce330bb81c.

<details>
<summary>Traceback</summary>

```
continuing from previous epoch - 16
Traceback (most recent call last):
  File "/usr/local/bin/stylegan2_pytorch", line 87, in <module>
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/bin/stylegan2_pytorch", line 59, in train_from_folder
    model.load(load_from)
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 947, in load
    self.GAN.load_state_dict(torch.load(self.model_name(name)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for StyleGAN2:
	size mismatch for G.initial_block: copying a param with shape torch.Size([64, 4, 4]) from checkpoint, the shape in current model is torch.Size([1, 512, 4, 4]).
	size mismatch for G.blocks.0.to_style1.weight: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for G.blocks.0.to_style1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for G.blocks.0.conv1.weight: copying a param with shape torch.Size([512, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for GE.initial_block: copying a param with shape torch.Size([64, 4, 4]) from checkpoint, the shape in current model is torch.Size([1, 512, 4, 4]).
	size mismatch for GE.blocks.0.to_style1.weight: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for GE.blocks.0.to_style1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for GE.blocks.0.conv1.weight: copying a param with shape torch.Size([512, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
```

</details>

**Comment by lucidrains** [comment]
@NickAcPT yea, unfortunately the architecture changed, which is why I did a minor version bump. you'll have to retrain, or stick to the old version if you still want your old model

**Comment by NickAcPT** [comment]
Makes sense. Closing this issue.
