### ISSUE TITLE
Crash when resuming from previous checkpoint

### ISSUE THREAD

**Issue by bob80333** [lucidrains/stylegan2-pytorch#87]
Pretty easy to reproduce.  Use any dataset, train for a few steps, resume from previous checkpoint.
```
Traceback (most recent call last):
  File "/usr/local/bin/stylegan2_pytorch", line 90, in <module>
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/bin/stylegan2_pytorch", line 87, in train_from_folder
    model.print_log()
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 936, in print_log
    print(f'G: {self.g_loss:.2f} | D: {self.d_loss:.2f} | GP: {self.last_gp_loss:.2f} | PL: {self.pl_mean:.2f} | CR: {self.last_cr_loss:.2f} | Q: {self.q_loss:.2f}')
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by lucidrains** [comment]
Oops, fixed in the latest! thanks for reporting!
