### ISSUE TITLE
How to use the code？

### ISSUE THREAD

**Issue by HuangLian126** [lucidrains/stylegan2-pytorch#89]
I have done the 'stylegan2_pytorch --data /path/to/images', however I get following error:

Traceback (most recent call last):
  File "E:/stylegan2-pytorch-master/bin/stylegan2_pytorch", line 5, in <module>
    from stylegan2_pytorch import Trainer, NanException
  File "E:\stylegan2-pytorch-master\stylegan2_pytorch\__init__.py", line 1, in <module>
    from stylegan2_pytorch.stylegan2_pytorch import Trainer, StyleGAN2, NanException
  File "E:\stylegan2-pytorch-master\stylegan2_pytorch\stylegan2_pytorch.py", line 27, in <module>
    from contrastive_learner import ContrastiveLearner
  File "D:\Anaconda\envs\python37\lib\site-packages\contrastive_learner\__init__.py", line 1, in <module>
    from contrastive_learner.contrastive_learner import ContrastiveLearner
  File "D:\Anaconda\envs\python37\lib\site-packages\contrastive_learner\contrastive_learner.py", line 10, in <module>
    from kornia import augmentation as augs
  File "D:\Anaconda\envs\python37\lib\site-packages\kornia\__init__.py", line 18, in <module>
    from kornia import jit
  File "D:\Anaconda\envs\python37\lib\site-packages\kornia\jit\__init__.py", line 8, in <module>
    spatial_soft_argmax2d = torch.jit.script(K.geometry.spatial_soft_argmax2d)
  File "D:\Anaconda\envs\python37\lib\site-packages\torch\jit\__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "D:\Anaconda\envs\python37\lib\site-packages\torch\jit\__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
  File "D:\Anaconda\envs\python37\lib\site-packages\torch\jit\__init__.py", line 1010, in _try_compile_fn
    return _compile_function(fn, qualified_name=qualified_name, _frames_up=1, _rcb=rcb)
  File "D:\Anaconda\envs\python37\lib\site-packages\torch\jit\__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
  File "D:\Anaconda\envs\python37\lib\site-packages\torch\jit\__init__.py", line 1010, in _try_compile_fn
    return _compile_function(fn, qualified_name=qualified_name, _frames_up=1, _rcb=rcb)
  File "D:\Anaconda\envs\python37\lib\site-packages\torch\jit\__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
RuntimeError: 
Unknown type name 'torch.device':
at D:\Anaconda\envs\python37\lib\site-packages\kornia\utils\grid.py:10:26
def create_meshgrid(
        height: int,
        width: int,
        normalized_coordinates: bool = True,
        device: Optional[torch.device] = torch.device('cpu')) -> torch.Tensor:
                         ~~~~~~~~~~~~ <--- HERE
    """Generates a coordinate grid for an image.

    When the flag `normalized_coordinates` is set to True, the grid is
    normalized to be in the range [-1,1] to be consistent with the pytorch
    function grid_sample.
    http://pytorch.org/docs/master/nn.html#torch.nn.functional.grid_sample

    Args:
        height (int): the image height (rows).'create_meshgrid' is being compiled since it was called from 'spatial_expectation2d'
at D:\Anaconda\envs\python37\lib\site-packages\kornia\geometry\dsnt.py:89:5
            [0., 1., 0.]]]])
        >>> coords = spatial_expectation_2d(heatmaps, False)
        tensor([[[1.0000, 2.0000]]])
    """
    _validate_batched_image_tensor_input(input)

    batch_size, channels, height, width = input.shape

    # Create coordinates grid.
    grid: torch.Tensor = create_meshgrid(height, width, normalized_coordinates, input.device)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    grid = grid.to(input.dtype)

    pos_x: torch.Tensor = grid[..., 0].reshape(-1)
    pos_y: torch.Tensor = grid[..., 1].reshape(-1)

    input_flat: torch.Tensor = input.view(batch_size, channels, -1)

    # Compute the expectation of the coordinates.
    expected_y: torch.Tensor = torch.sum(pos_y * input_flat, -1, keepdim=True)'spatial_expectation2d' is being compiled since it was called from 'spatial_soft_argmax2d'
at D:\Anaconda\envs\python37\lib\site-packages\kornia\geometry\spatial_soft_argmax.py:515:5
    Examples:
        >>> input = torch.tensor([[[
            [0., 0., 0.],
            [0., 10., 0.],
            [0., 0., 0.]]]])
        >>> coords = kornia.spatial_soft_argmax2d(input, False)
        tensor([[[1.0000, 1.0000]]])
    """
    input_soft: torch.Tensor = dsnt.spatial_softmax2d(input, temperature)
    output: torch.Tensor = dsnt.spatial_expectation2d(input_soft, normalized_coordinates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return output

Can you help me?

**Comment by LvanderGoten** [comment]
I second that

**Comment by lucidrains** [comment]
@LvanderGoten are you using windows as well?

**Comment by lucidrains** [comment]
@LvanderGoten i should probably remove the contrastive learning feature (and Kornia), it's been nothing but trouble lol

**Comment by LvanderGoten** [comment]
No I am solely using Linux together with Conda

**Comment by lucidrains** [comment]
@LvanderGoten ok, got it, can you try version `0.17.10` and see if that fixes things?

**Comment by lucidrains** [comment]
hmm, i'm guessing it is fixed and closing
