### ISSUE TITLE
num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by dmd** [lucidrains/stylegan2-pytorch#91]
Like #11 but earlier in the process:

```
ddrucker@node5 ~$ python3 -m venv sty

ddrucker@node5 ~$ . sty/bin/activate

(sty)
ddrucker@node5 ~$ pip install stylegan2_pytorch
Collecting stylegan2_pytorch
 ```
(etc etc etc)

```
(sty)
ddrucker@node5 ~$ stylegan2_pytorch --data ~/small --name capy
Traceback (most recent call last):
  File "/home/ddrucker/sty/bin/stylegan2_pytorch", line 90, in <module>
    fire.Fire(train_from_folder)
  File "/home/ddrucker/sty/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ddrucker/sty/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/ddrucker/sty/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ddrucker/sty/bin/stylegan2_pytorch", line 82, in train_from_folder
    model.set_data_src(data)
  File "/home/ddrucker/sty/lib/python3.7/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 680, in set_data_src
    self.loader = cycle(data.DataLoader(self.dataset, num_workers = default(self.num_workers, num_cores), batch_size = self.batch_size, drop_last = True, shuffle=True, pin_memory=True))
  File "/home/ddrucker/sty/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/ddrucker/sty/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
(sty)
ddrucker@node5 ~$ 
```

**Comment by dmd** [comment]
Never mind, my filenames were `.jpeg` instead of `.jpg`.
